const searchData = [
    {
        image: "../../img/hotel1.png",
        title: "Hytt Ahedabad",
        distance: "500m from Apartment",
        taxiOp : "Free Airtport Taxi",
        subTitle : "Studio Apartment with Air Conditiong", 
        feature: "Entire Studio",
        cancelOp: "Free Cancellation",
        rating : "Excellent",
        ratingBtn : "8.9",
        price: "$789",
        tax: "Includes tax and fees",
    },
    {
        image: "../../img/hotel2.png",
        title: "Hotel Good night",
        distance: "267m from Apartment",
        taxiOp : "Charge Included",
        subTitle : "Studio Apartment with Air Conditiong", 
        feature: "Entire Studio",
        cancelOp: "Free Cancellation",
        rating : "Good",
        ratingBtn : "6.5",
        price: "$123",
        tax: "Includes tax and fees",
    },
    {
        image: "../../img/hotel3.png",
        title: "Hotel Dream Inn",
        distance: "378m from Apartment",
        taxiOp : "Taxi Charges Included",
        subTitle : "Studio Apartment with Air Conditiong", 
        feature: "Entire Studio",
        cancelOp: "Free Cancellation",
        rating : "Average",
        ratingBtn : "7.6",
        price: "$345",
        tax: "Includes tax and fees",
    },
    {
        image: "../../img/hotel5.png",
        title: "Hotel Green Tree",
        distance: "267m from Apartment",
        taxiOp : "Charge Included",
        subTitle : "Studio Apartment with Air Conditiong", 
        feature: "Entire Studio",
        cancelOp: "Free Cancellation",
        rating : "Good",
        ratingBtn : "6.5",
        price: "$456",
        tax: "Includes tax and fees",
    },
    {
        image: "../../img/hotel6.png",
        title: "Hotel GGC Inn",
        distance: "98m from Apartment",
        taxiOp : "Free Taxi Service",
        subTitle : "Studio Apartment with Air Conditiong", 
        feature: "Entire Studio",
        cancelOp: "Free Cancellation",
        rating : "Good",
        ratingBtn : "6.5",
        price: "$456",
        tax: "Includes tax and fees",
    },
    {
        image: "../../img/hotel7.png",
        title: "Fab Express Gokul Villa",
        distance: "678m from Apartment",
        taxiOp : "Free Taxi/ No Charges",
        subTitle : "Studio Apartment with Air Conditiong", 
        feature: "Entire Studio",
        cancelOp: "Free Cancellation",
        rating : "Fabulous",
        ratingBtn : "7.8",
        price: "$456",
        tax: "Includes tax and fees",
    },
    {
        image: "../../img/hotel8.png",
        title: "Terazzo Suits",
        distance: "267m from Apartment",
        taxiOp : "Charge Included",
        subTitle : "Studio Apartment with Air Conditiong", 
        feature: "Entire Studio",
        cancelOp: "Free Cancellation",
        rating : "Good",
        ratingBtn : "6.5",
        price: "$89",
        tax: "Includes tax and fees",
    }
]

export default searchData;